### ISSUE TITLE
SWA causing crash at end of training

### ISSUE THREAD

**Issue by cwerner** [cwerner/deadtrees#69]
Enabling stochastic weight averaging (SWA) causes an out-of-memory late in the training. This seems to be a known bug in pytorch lightning (issue: https://github.com/PyTorchLightning/pytorch-lightning/issues/9441).

Try to investigate with few epochs. Also, check if one can lower/ half the `batch_size` at the last (?) epoch when SWA crash occurs.

**Comment by cwerner** [comment]
Waiting for upstream fix before enabling `SWA` again

**Comment by austinmw** [comment]
Hi @cwerner, is this fixed? In 1.6.3 I'm seeing CUDA OOM crashes at epoch 79/80 when using SWA
